export const LAB_TEST_SEED: { name: string; category: string; unit: string; referenceRange: string; price: number }[] = [
  { name: 'Hemoglobin (Hb)', category: 'Hematology', unit: 'g/dL', referenceRange: 'M: 13.5-17.5, F: 12.0-15.5', price: 5 },
  { name: 'Hematocrit (PCV)', category: 'Hematology', unit: '%', referenceRange: 'M: 40-52, F: 36-48', price: 5 },
  { name: 'Red Blood Cell Count (RBC)', category: 'Hematology', unit: '10^6/uL', referenceRange: '4.2-5.9', price: 6 },
  { name: 'White Blood Cell Count (WBC)', category: 'Hematology', unit: '10^3/uL', referenceRange: '4.0-11.0', price: 6 },
  { name: 'Platelet Count', category: 'Hematology', unit: '10^3/uL', referenceRange: '150-450', price: 6 },
  { name: 'Mean Corpuscular Volume (MCV)', category: 'Hematology', unit: 'fL', referenceRange: '80-100', price: 4 },
  { name: 'Mean Corpuscular Hemoglobin (MCH)', category: 'Hematology', unit: 'pg', referenceRange: '27-33', price: 4 },
  { name: 'Mean Corpuscular Hemoglobin Concentration (MCHC)', category: 'Hematology', unit: 'g/dL', referenceRange: '32-36', price: 4 },
  { name: 'Red Cell Distribution Width (RDW)', category: 'Hematology', unit: '%', referenceRange: '11.5-14.5', price: 4 },
  { name: 'Neutrophils', category: 'Hematology', unit: '%', referenceRange: '40-75', price: 4 },
  { name: 'Lymphocytes', category: 'Hematology', unit: '%', referenceRange: '20-45', price: 4 },
  { name: 'Monocytes', category: 'Hematology', unit: '%', referenceRange: '2-10', price: 4 },
  { name: 'Eosinophils', category: 'Hematology', unit: '%', referenceRange: '1-6', price: 4 },
  { name: 'Basophils', category: 'Hematology', unit: '%', referenceRange: '0-2', price: 4 },
  { name: 'Absolute Neutrophil Count', category: 'Hematology', unit: '10^3/uL', referenceRange: '2.0-7.5', price: 6 },
  { name: 'Absolute Lymphocyte Count', category: 'Hematology', unit: '10^3/uL', referenceRange: '1.0-4.0', price: 6 },
  { name: 'Erythrocyte Sedimentation Rate (ESR)', category: 'Hematology', unit: 'mm/hr', referenceRange: 'M: 0-15, F: 0-20', price: 5 },
  { name: 'Reticulocyte Count', category: 'Hematology', unit: '%', referenceRange: '0.5-2.5', price: 8 },
  { name: 'Peripheral Blood Smear', category: 'Hematology', unit: '-', referenceRange: 'Normal morphology', price: 10 },
  { name: 'Blood Group & Rh Typing', category: 'Hematology', unit: '-', referenceRange: 'Reported', price: 6 },
  { name: 'Direct Coombs Test', category: 'Hematology', unit: '-', referenceRange: 'Negative', price: 10 },
  { name: 'Indirect Coombs Test', category: 'Hematology', unit: '-', referenceRange: 'Negative', price: 10 },
  { name: 'Prothrombin Time (PT)', category: 'Coagulation', unit: 'sec', referenceRange: '11-13.5', price: 10 },
  { name: 'International Normalized Ratio (INR)', category: 'Coagulation', unit: 'ratio', referenceRange: '0.8-1.1', price: 8 },
  { name: 'Activated Partial Thromboplastin Time (aPTT)', category: 'Coagulation', unit: 'sec', referenceRange: '25-35', price: 10 },
  { name: 'Fibrinogen', category: 'Coagulation', unit: 'mg/dL', referenceRange: '200-400', price: 12 },
  { name: 'D-Dimer', category: 'Coagulation', unit: 'ug/mL FEU', referenceRange: '< 0.5', price: 20 },
  { name: 'Bleeding Time', category: 'Coagulation', unit: 'min', referenceRange: '2-7', price: 5 },
  { name: 'Clotting Time', category: 'Coagulation', unit: 'min', referenceRange: '5-10', price: 5 },
  { name: 'Blood Urea Nitrogen (BUN)', category: 'Renal', unit: 'mg/dL', referenceRange: '7-20', price: 6 },
  { name: 'Urea', category: 'Renal', unit: 'mg/dL', referenceRange: '15-45', price: 6 },
  { name: 'Creatinine', category: 'Renal', unit: 'mg/dL', referenceRange: '0.6-1.3', price: 6 },
  { name: 'Estimated GFR (eGFR)', category: 'Renal', unit: 'mL/min/1.73m2', referenceRange: '> 90', price: 6 },
  { name: 'Uric Acid', category: 'Renal', unit: 'mg/dL', referenceRange: 'M: 3.4-7.0, F: 2.4-6.0', price: 8 },
  { name: 'Sodium (Na+)', category: 'Electrolytes', unit: 'mmol/L', referenceRange: '135-145', price: 6 },
  { name: 'Potassium (K+)', category: 'Electrolytes', unit: 'mmol/L', referenceRange: '3.5-5.1', price: 6 },
  { name: 'Chloride (Cl-)', category: 'Electrolytes', unit: 'mmol/L', referenceRange: '98-107', price: 6 },
  { name: 'Bicarbonate (HCO3-)', category: 'Electrolytes', unit: 'mmol/L', referenceRange: '22-29', price: 6 },
  { name: 'Calcium, Total', category: 'Electrolytes', unit: 'mg/dL', referenceRange: '8.5-10.5', price: 7 },
  { name: 'Calcium, Ionized', category: 'Electrolytes', unit: 'mmol/L', referenceRange: '1.1-1.3', price: 10 },
  { name: 'Phosphorus', category: 'Electrolytes', unit: 'mg/dL', referenceRange: '2.5-4.5', price: 7 },
  { name: 'Magnesium', category: 'Electrolytes', unit: 'mg/dL', referenceRange: '1.7-2.2', price: 8 },
  { name: 'Alanine Aminotransferase (ALT/SGPT)', category: 'Liver Function', unit: 'U/L', referenceRange: '7-56', price: 7 },
  { name: 'Aspartate Aminotransferase (AST/SGOT)', category: 'Liver Function', unit: 'U/L', referenceRange: '8-48', price: 7 },
  { name: 'Alkaline Phosphatase (ALP)', category: 'Liver Function', unit: 'U/L', referenceRange: '44-147', price: 7 },
  { name: 'Gamma-Glutamyl Transferase (GGT)', category: 'Liver Function', unit: 'U/L', referenceRange: '8-61', price: 8 },
  { name: 'Total Bilirubin', category: 'Liver Function', unit: 'mg/dL', referenceRange: '0.1-1.2', price: 6 },
  { name: 'Direct (Conjugated) Bilirubin', category: 'Liver Function', unit: 'mg/dL', referenceRange: '0.0-0.3', price: 6 },
  { name: 'Indirect (Unconjugated) Bilirubin', category: 'Liver Function', unit: 'mg/dL', referenceRange: '0.1-0.9', price: 6 },
  { name: 'Total Protein', category: 'Liver Function', unit: 'g/dL', referenceRange: '6.0-8.3', price: 6 },
  { name: 'Albumin', category: 'Liver Function', unit: 'g/dL', referenceRange: '3.5-5.0', price: 6 },
  { name: 'Globulin', category: 'Liver Function', unit: 'g/dL', referenceRange: '2.0-3.5', price: 6 },
  { name: 'Albumin/Globulin (A/G) Ratio', category: 'Liver Function', unit: 'ratio', referenceRange: '1.0-2.5', price: 5 },
  { name: 'Lactate Dehydrogenase (LDH)', category: 'Liver Function', unit: 'U/L', referenceRange: '140-280', price: 9 },
  { name: 'Total Cholesterol', category: 'Lipid Profile', unit: 'mg/dL', referenceRange: '< 200', price: 8 },
  { name: 'Triglycerides', category: 'Lipid Profile', unit: 'mg/dL', referenceRange: '< 150', price: 8 },
  { name: 'HDL Cholesterol', category: 'Lipid Profile', unit: 'mg/dL', referenceRange: 'M: > 40, F: > 50', price: 8 },
  { name: 'LDL Cholesterol', category: 'Lipid Profile', unit: 'mg/dL', referenceRange: '< 100', price: 8 },
  { name: 'VLDL Cholesterol', category: 'Lipid Profile', unit: 'mg/dL', referenceRange: '5-40', price: 8 },
  { name: 'Cholesterol/HDL Ratio', category: 'Lipid Profile', unit: 'ratio', referenceRange: '< 5.0', price: 5 },
  { name: 'Fasting Blood Glucose (FBG)', category: 'Glucose', unit: 'mg/dL', referenceRange: '70-100', price: 5 },
  { name: 'Random Blood Glucose (RBG)', category: 'Glucose', unit: 'mg/dL', referenceRange: '70-140', price: 5 },
  { name: 'Postprandial Glucose (2h PP)', category: 'Glucose', unit: 'mg/dL', referenceRange: '70-140', price: 5 },
  { name: 'Oral Glucose Tolerance Test (2hr)', category: 'Glucose', unit: 'mg/dL', referenceRange: '< 140', price: 12 },
  { name: 'Hemoglobin A1c (HbA1c)', category: 'Glucose', unit: '%', referenceRange: '4.0-5.6', price: 15 },
  { name: 'Fasting Insulin', category: 'Glucose', unit: 'uIU/mL', referenceRange: '2.6-24.9', price: 20 },
  { name: 'C-Peptide', category: 'Glucose', unit: 'ng/mL', referenceRange: '0.8-3.9', price: 22 },
  { name: 'Troponin I', category: 'Cardiac', unit: 'ng/mL', referenceRange: '< 0.04', price: 25 },
  { name: 'Troponin T, High-Sensitivity', category: 'Cardiac', unit: 'ng/L', referenceRange: '< 14', price: 28 },
  { name: 'Creatine Kinase-MB (CK-MB)', category: 'Cardiac', unit: 'ng/mL', referenceRange: '0-5', price: 15 },
  { name: 'Creatine Kinase, Total (CK-Total)', category: 'Cardiac', unit: 'U/L', referenceRange: '30-200', price: 10 },
  { name: 'Myoglobin', category: 'Cardiac', unit: 'ng/mL', referenceRange: '25-72', price: 18 },
  { name: 'BNP', category: 'Cardiac', unit: 'pg/mL', referenceRange: '< 100', price: 30 },
  { name: 'NT-proBNP', category: 'Cardiac', unit: 'pg/mL', referenceRange: '< 125', price: 30 },
  { name: 'Thyroid Stimulating Hormone (TSH)', category: 'Thyroid', unit: 'uIU/mL', referenceRange: '0.4-4.0', price: 12 },
  { name: 'Free T4 (FT4)', category: 'Thyroid', unit: 'ng/dL', referenceRange: '0.8-1.8', price: 12 },
  { name: 'Free T3 (FT3)', category: 'Thyroid', unit: 'pg/mL', referenceRange: '2.3-4.2', price: 12 },
  { name: 'Total T4', category: 'Thyroid', unit: 'ug/dL', referenceRange: '5.0-12.0', price: 10 },
  { name: 'Total T3', category: 'Thyroid', unit: 'ng/dL', referenceRange: '80-200', price: 10 },
  { name: 'Anti-TPO Antibodies', category: 'Thyroid', unit: 'IU/mL', referenceRange: '< 35', price: 18 },
  { name: 'Thyroglobulin Antibodies', category: 'Thyroid', unit: 'IU/mL', referenceRange: '< 40', price: 18 },
  { name: 'C-Reactive Protein (CRP)', category: 'Inflammatory', unit: 'mg/L', referenceRange: '< 5', price: 8 },
  { name: 'High-Sensitivity CRP (hs-CRP)', category: 'Inflammatory', unit: 'mg/L', referenceRange: '< 1.0', price: 12 },
  { name: 'Rheumatoid Factor (RF)', category: 'Immunology', unit: 'IU/mL', referenceRange: '< 14', price: 8 },
  { name: 'Anti-Nuclear Antibody (ANA)', category: 'Immunology', unit: 'titer', referenceRange: '< 1:80', price: 20 },
  { name: 'Anti-dsDNA Antibody', category: 'Immunology', unit: 'IU/mL', referenceRange: '< 30', price: 22 },
  { name: 'Procalcitonin', category: 'Immunology', unit: 'ng/mL', referenceRange: '< 0.05', price: 25 },
  { name: 'Complement C3', category: 'Immunology', unit: 'mg/dL', referenceRange: '90-180', price: 15 },
  { name: 'Complement C4', category: 'Immunology', unit: 'mg/dL', referenceRange: '10-40', price: 15 },
  { name: 'Anti-CCP Antibody', category: 'Immunology', unit: 'U/mL', referenceRange: '< 20', price: 25 },
  { name: 'HLA-B27', category: 'Immunology', unit: '-', referenceRange: 'Negative', price: 30 },
  { name: 'Anti-Mitochondrial Antibody (AMA)', category: 'Immunology', unit: 'titer', referenceRange: 'Negative', price: 22 },
  { name: 'Anti-Smooth Muscle Antibody (ASMA)', category: 'Immunology', unit: 'titer', referenceRange: 'Negative', price: 22 },
  { name: 'Hepatitis B Surface Antigen (HBsAg)', category: 'Serology', unit: '-', referenceRange: 'Negative', price: 10 },
  { name: 'Hepatitis B Surface Antibody (Anti-HBs)', category: 'Serology', unit: 'mIU/mL', referenceRange: '> 10', price: 10 },
  { name: 'Hepatitis B Core Antibody (Anti-HBc)', category: 'Serology', unit: '-', referenceRange: 'Negative', price: 12 },
  { name: 'Hepatitis C Antibody (Anti-HCV)', category: 'Serology', unit: '-', referenceRange: 'Negative', price: 12 },
  { name: 'HIV 1/2 Antibody (Rapid Test)', category: 'Serology', unit: '-', referenceRange: 'Non-reactive', price: 8 },
  { name: 'HIV Antigen/Antibody Combo', category: 'Serology', unit: '-', referenceRange: 'Non-reactive', price: 15 },
  { name: 'VDRL / RPR (Syphilis)', category: 'Serology', unit: '-', referenceRange: 'Non-reactive', price: 6 },
  { name: 'TPHA (Syphilis Confirmatory)', category: 'Serology', unit: '-', referenceRange: 'Non-reactive', price: 10 },
  { name: 'Malaria Rapid Diagnostic Test (RDT)', category: 'Serology', unit: '-', referenceRange: 'Negative', price: 5 },
  { name: 'Malaria Blood Film (Thick & Thin)', category: 'Microscopy', unit: '-', referenceRange: 'No parasites seen', price: 6 },
  { name: 'Widal Test (Typhoid)', category: 'Serology', unit: 'titer', referenceRange: '< 1:80', price: 6 },
  { name: 'Dengue NS1 Antigen', category: 'Serology', unit: '-', referenceRange: 'Negative', price: 12 },
  { name: 'Dengue IgM Antibody', category: 'Serology', unit: '-', referenceRange: 'Negative', price: 12 },
  { name: 'Dengue IgG Antibody', category: 'Serology', unit: '-', referenceRange: 'Negative', price: 12 },
  { name: 'Brucella Agglutination Test', category: 'Serology', unit: 'titer', referenceRange: '< 1:80', price: 8 },
  { name: 'H. pylori Stool Antigen', category: 'Serology', unit: '-', referenceRange: 'Negative', price: 10 },
  { name: 'H. pylori Antibody (Blood)', category: 'Serology', unit: '-', referenceRange: 'Negative', price: 10 },
  { name: 'Toxoplasma IgG', category: 'Serology', unit: 'IU/mL', referenceRange: '< 3.0', price: 12 },
  { name: 'Toxoplasma IgM', category: 'Serology', unit: '-', referenceRange: 'Negative', price: 12 },
  { name: 'Rubella IgG', category: 'Serology', unit: 'IU/mL', referenceRange: '> 10', price: 12 },
  { name: 'Rubella IgM', category: 'Serology', unit: '-', referenceRange: 'Negative', price: 12 },
  { name: 'Measles IgG', category: 'Serology', unit: '-', referenceRange: 'Immune', price: 12 },
  { name: 'Chikungunya IgM', category: 'Serology', unit: '-', referenceRange: 'Negative', price: 15 },
  { name: 'COVID-19 Antigen (Rapid)', category: 'Serology', unit: '-', referenceRange: 'Negative', price: 8 },
  { name: 'COVID-19 PCR', category: 'Molecular', unit: '-', referenceRange: 'Not detected', price: 25 },
  { name: 'Tuberculosis Gene Xpert', category: 'Molecular', unit: '-', referenceRange: 'Not detected', price: 20 },
  { name: 'Mantoux Test (TB Skin Test)', category: 'Serology', unit: 'mm induration', referenceRange: '< 5 mm', price: 6 },
  { name: 'Quantiferon TB Gold (IGRA)', category: 'Serology', unit: '-', referenceRange: 'Negative', price: 30 },
  { name: 'Vitamin D (25-OH)', category: 'Vitamins', unit: 'ng/mL', referenceRange: '30-100', price: 25 },
  { name: 'Vitamin B12', category: 'Vitamins', unit: 'pg/mL', referenceRange: '200-900', price: 18 },
  { name: 'Folate (Folic Acid)', category: 'Vitamins', unit: 'ng/mL', referenceRange: '2.7-17.0', price: 18 },
  { name: 'Ferritin', category: 'Iron Studies', unit: 'ng/mL', referenceRange: 'M: 24-336, F: 11-307', price: 15 },
  { name: 'Serum Iron', category: 'Iron Studies', unit: 'ug/dL', referenceRange: '60-170', price: 8 },
  { name: 'Total Iron Binding Capacity (TIBC)', category: 'Iron Studies', unit: 'ug/dL', referenceRange: '240-450', price: 10 },
  { name: 'Transferrin Saturation', category: 'Iron Studies', unit: '%', referenceRange: '20-50', price: 8 },
  { name: 'Zinc', category: 'Minerals', unit: 'ug/dL', referenceRange: '60-120', price: 15 },
  { name: 'Copper', category: 'Minerals', unit: 'ug/dL', referenceRange: '70-140', price: 15 },
  { name: 'Ceruloplasmin', category: 'Minerals', unit: 'mg/dL', referenceRange: '20-35', price: 18 },
  { name: 'Beta-hCG (Qualitative Pregnancy Test)', category: 'Hormones', unit: '-', referenceRange: 'Negative', price: 6 },
  { name: 'Beta-hCG (Quantitative)', category: 'Hormones', unit: 'mIU/mL', referenceRange: '< 5', price: 15 },
  { name: 'Follicle Stimulating Hormone (FSH)', category: 'Hormones', unit: 'mIU/mL', referenceRange: '1.5-12.4', price: 15 },
  { name: 'Luteinizing Hormone (LH)', category: 'Hormones', unit: 'mIU/mL', referenceRange: '1.7-8.6', price: 15 },
  { name: 'Prolactin', category: 'Hormones', unit: 'ng/mL', referenceRange: '4.0-23.0', price: 15 },
  { name: 'Estradiol', category: 'Hormones', unit: 'pg/mL', referenceRange: '15-350', price: 18 },
  { name: 'Progesterone', category: 'Hormones', unit: 'ng/mL', referenceRange: '0.2-25', price: 18 },
  { name: 'Testosterone, Total', category: 'Hormones', unit: 'ng/dL', referenceRange: 'M: 264-916, F: 15-70', price: 18 },
  { name: 'Testosterone, Free', category: 'Hormones', unit: 'pg/mL', referenceRange: 'M: 8.7-25.1, F: 0.2-5.0', price: 22 },
  { name: 'Cortisol, AM', category: 'Hormones', unit: 'ug/dL', referenceRange: '6.2-19.4', price: 18 },
  { name: 'DHEA-Sulfate', category: 'Hormones', unit: 'ug/dL', referenceRange: '65-380', price: 20 },
  { name: 'PSA, Total', category: 'Hormones', unit: 'ng/mL', referenceRange: '< 4.0', price: 15 },
  { name: 'PSA, Free', category: 'Hormones', unit: 'ng/mL', referenceRange: '> 25% of total', price: 18 },
  { name: 'Growth Hormone (GH)', category: 'Hormones', unit: 'ng/mL', referenceRange: '0-5', price: 22 },
  { name: 'Anti-Mullerian Hormone (AMH)', category: 'Hormones', unit: 'ng/mL', referenceRange: '1.0-4.0', price: 30 },
  { name: 'Parathyroid Hormone (PTH)', category: 'Hormones', unit: 'pg/mL', referenceRange: '15-65', price: 22 },
  { name: 'Urine Routine & Microscopy', category: 'Urinalysis', unit: '-', referenceRange: 'Normal', price: 5 },
  { name: 'Urine pH', category: 'Urinalysis', unit: '-', referenceRange: '4.5-8.0', price: 3 },
  { name: 'Urine Specific Gravity', category: 'Urinalysis', unit: '-', referenceRange: '1.005-1.030', price: 3 },
  { name: 'Urine Protein (Dipstick)', category: 'Urinalysis', unit: '-', referenceRange: 'Negative', price: 3 },
  { name: 'Urine Glucose (Dipstick)', category: 'Urinalysis', unit: '-', referenceRange: 'Negative', price: 3 },
  { name: 'Urine Ketones', category: 'Urinalysis', unit: '-', referenceRange: 'Negative', price: 3 },
  { name: 'Urine Blood (Dipstick)', category: 'Urinalysis', unit: '-', referenceRange: 'Negative', price: 3 },
  { name: 'Urine Leukocyte Esterase', category: 'Urinalysis', unit: '-', referenceRange: 'Negative', price: 3 },
  { name: 'Urine Nitrites', category: 'Urinalysis', unit: '-', referenceRange: 'Negative', price: 3 },
  { name: 'Urine Microalbumin', category: 'Urinalysis', unit: 'mg/L', referenceRange: '< 20', price: 15 },
  { name: 'Urine Microalbumin/Creatinine Ratio', category: 'Urinalysis', unit: 'mg/g', referenceRange: '< 30', price: 18 },
  { name: '24-Hour Urine Protein', category: 'Urinalysis', unit: 'mg/24h', referenceRange: '< 150', price: 20 },
  { name: '24-Hour Urine Creatinine Clearance', category: 'Urinalysis', unit: 'mL/min', referenceRange: '90-130', price: 20 },
  { name: 'Stool Routine & Microscopy', category: 'Stool', unit: '-', referenceRange: 'No ova/parasites/blood', price: 5 },
  { name: 'Stool Occult Blood (FOBT)', category: 'Stool', unit: '-', referenceRange: 'Negative', price: 6 },
  { name: 'Stool Ova & Parasites', category: 'Stool', unit: '-', referenceRange: 'Not detected', price: 8 },
  { name: 'Stool Culture & Sensitivity', category: 'Microbiology', unit: '-', referenceRange: 'No pathogens isolated', price: 15 },
  { name: 'Fecal Calprotectin', category: 'Stool', unit: 'ug/g', referenceRange: '< 50', price: 25 },
  { name: 'Carcinoembryonic Antigen (CEA)', category: 'Tumor Markers', unit: 'ng/mL', referenceRange: '< 3.0', price: 20 },
  { name: 'Alpha-Fetoprotein (AFP)', category: 'Tumor Markers', unit: 'ng/mL', referenceRange: '< 10', price: 20 },
  { name: 'CA-125', category: 'Tumor Markers', unit: 'U/mL', referenceRange: '< 35', price: 22 },
  { name: 'CA 19-9', category: 'Tumor Markers', unit: 'U/mL', referenceRange: '< 37', price: 22 },
  { name: 'CA 15-3', category: 'Tumor Markers', unit: 'U/mL', referenceRange: '< 30', price: 22 },
  { name: 'Arterial Blood Gas - pH', category: 'Blood Gas', unit: '-', referenceRange: '7.35-7.45', price: 20 },
  { name: 'Arterial Blood Gas - pCO2', category: 'Blood Gas', unit: 'mmHg', referenceRange: '35-45', price: 20 },
  { name: 'Arterial Blood Gas - pO2', category: 'Blood Gas', unit: 'mmHg', referenceRange: '80-100', price: 20 },
  { name: 'Arterial Blood Gas - HCO3', category: 'Blood Gas', unit: 'mmol/L', referenceRange: '22-26', price: 20 },
  { name: 'Lactate (Blood)', category: 'Blood Gas', unit: 'mmol/L', referenceRange: '0.5-2.2', price: 15 },
  { name: 'Amylase', category: 'Pancreatic', unit: 'U/L', referenceRange: '30-110', price: 8 },
  { name: 'Lipase', category: 'Pancreatic', unit: 'U/L', referenceRange: '10-140', price: 10 },
  { name: 'Fecal Elastase', category: 'Pancreatic', unit: 'ug/g', referenceRange: '> 200', price: 25 },
  { name: 'Blood Alcohol Level', category: 'Toxicology', unit: 'mg/dL', referenceRange: '0', price: 15 },
  { name: 'Paracetamol (Acetaminophen) Level', category: 'Toxicology', unit: 'ug/mL', referenceRange: '10-20', price: 18 },
  { name: 'Digoxin Level', category: 'Toxicology', unit: 'ng/mL', referenceRange: '0.8-2.0', price: 20 },
  { name: 'Lithium Level', category: 'Toxicology', unit: 'mmol/L', referenceRange: '0.6-1.2', price: 18 },
  { name: 'Phenytoin Level', category: 'Toxicology', unit: 'ug/mL', referenceRange: '10-20', price: 18 },
  { name: 'Carbamazepine Level', category: 'Toxicology', unit: 'ug/mL', referenceRange: '4-12', price: 18 },
  { name: 'Valproic Acid Level', category: 'Toxicology', unit: 'ug/mL', referenceRange: '50-100', price: 18 },
  { name: 'Blood Culture & Sensitivity', category: 'Microbiology', unit: '-', referenceRange: 'No growth', price: 25 },
  { name: 'Urine Culture & Sensitivity', category: 'Microbiology', unit: '-', referenceRange: 'No growth (< 10^3 CFU/mL)', price: 15 },
  { name: 'Sputum Culture & Sensitivity', category: 'Microbiology', unit: '-', referenceRange: 'Normal flora', price: 15 },
  { name: 'Throat Swab Culture', category: 'Microbiology', unit: '-', referenceRange: 'Normal flora', price: 12 },
  { name: 'Wound Swab Culture & Sensitivity', category: 'Microbiology', unit: '-', referenceRange: 'No growth', price: 15 },
  { name: 'CSF Analysis & Culture', category: 'Microbiology', unit: '-', referenceRange: 'Clear, no organisms', price: 30 },
  { name: 'Semen Analysis', category: 'Andrology', unit: '-', referenceRange: 'See WHO reference criteria', price: 15 },
  { name: 'Vaginal Swab Culture', category: 'Microbiology', unit: '-', referenceRange: 'Normal flora', price: 12 },
  { name: 'Ammonia', category: 'Metabolic', unit: 'umol/L', referenceRange: '15-45', price: 20 },
  { name: 'Homocysteine', category: 'Metabolic', unit: 'umol/L', referenceRange: '5-15', price: 22 },
  { name: 'Lipoprotein(a)', category: 'Lipid Profile', unit: 'mg/dL', referenceRange: '< 30', price: 25 },
  { name: 'Apolipoprotein B (ApoB)', category: 'Lipid Profile', unit: 'mg/dL', referenceRange: '< 100', price: 22 },
  { name: 'Apolipoprotein A1 (ApoA1)', category: 'Lipid Profile', unit: 'mg/dL', referenceRange: '120-160', price: 22 },
  { name: 'Alpha-1 Antitrypsin', category: 'Metabolic', unit: 'mg/dL', referenceRange: '100-200', price: 22 },
  { name: 'Osmolality, Serum', category: 'Metabolic', unit: 'mOsm/kg', referenceRange: '275-295', price: 12 },
  { name: 'Pap Smear (Cervical Cytology)', category: 'Cytology', unit: '-', referenceRange: 'Negative for intraepithelial lesion', price: 15 },
  { name: 'Fine Needle Aspiration Cytology (FNAC)', category: 'Cytology', unit: '-', referenceRange: 'Reported', price: 25 },
  { name: 'Body Fluid Cytology', category: 'Cytology', unit: '-', referenceRange: 'Reported', price: 22 },
  { name: 'Biopsy / Histopathology Report', category: 'Histopathology', unit: '-', referenceRange: 'Reported', price: 40 },
  { name: 'Pleural Fluid Analysis', category: 'Body Fluids', unit: '-', referenceRange: 'Reported', price: 25 },
  { name: 'Ascitic Fluid Analysis', category: 'Body Fluids', unit: '-', referenceRange: 'Reported', price: 25 },
  { name: 'Synovial Fluid Analysis', category: 'Body Fluids', unit: '-', referenceRange: 'Reported', price: 25 },
  { name: 'Cervical Swab Culture', category: 'Microbiology', unit: '-', referenceRange: 'Normal flora', price: 12 },
];
